#!/bin/bash

CONTAINER="RTMP"

build() {
  echo "Building... $CONTAINER"
  STDOUT=`docker build -t zfront/rtmp .`
}

clean() {
  echo "Cleaning $CONTAINER"
  STDOUT=`docker rm rtmp`
}

start() {
  echo "Starting... $CONTAINER"
  STDOUT=`docker run -d -h zfront -P -p 1935:1935 -p 80:80 -v $PWD/media:/tmp/stream --name=rtmp zfront/rtmp`
}

stop() {
  echo "Stoping... $CONTAINER"
  STDOUT=`docker stop rtmp`
}

attach() {
  echo "Attaching to... $CONTAINER"
  docker exec -it rtmp bash -l
}

case $1 in
	"build")
    build
	;;
  "clean")
    clean
  ;;
  "start")
    stop
    clean
    start
  ;;
  "stop")
    stop
  ;;
  "attach")
    attach
  ;;
  "help"|*)
    echo "./magic [CMD]"
    echo "-------------"
    echo "build - Build the docker image"
    echo "clean - Remove the docker image"
    echo "start - Start the docker container"
    echo "stop - Stop the docker container"
    echo "attach - Run a shell in the docker container"
  ;;
esac
